### ISSUE TITLE
A template for blank

### ISSUE THREAD

**Issue by icecodder** [starts-with/ask-for-templates#2]
*Please avoid the modification of the template, only answer questions...*

**Name of the template** *(You can include the name of some built-in modules, like `deno-oak`)*:
blank

**Describe the template, tech used, and why...**:
Just Blank

**List of things included in the template, such as the language/runtime, modules, configurations, best practices...** *(Include links to the resources if you can)*:
Nothing

**Do you want to be a maintainer *(custom access to the repository)* of the template ?**:
No

**People you know who can potentially be maintainers of the template? Or communities?** *(Please give links to profiles.)*:
No

**Other**
...

**Comment by n1c00o** [comment]
You can just go to https://github.com/new and create a repo :/
